plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "E:\\claude projects\\webagency-madrid\\websiteagency\\pumpum-mockup"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]